/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsCategoryRouteImport } from './routes/products/$category'
import { Route as ProductsCategoryProductRouteImport } from './routes/products/$category/$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryProductRoute = ProductsCategoryProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => ProductsCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/products': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$category': typeof ProductsCategoryRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/products/$category' | '/products/' | '/products/$category/$product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$category' | '/products' | '/products/$category/$product'
  id:
    | '__root__'
    | '/'
    | '/products/$category'
    | '/products/'
    | '/products/$category/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsCategoryRoute: typeof ProductsCategoryRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/$product': {
      id: '/products/$category/$product'
      path: '/$product'
      fullPath: '/products/$category/$product'
      preLoaderRoute: typeof ProductsCategoryProductRouteImport
      parentRoute: typeof ProductsCategoryRoute
    }
  }
}

interface ProductsCategoryRouteChildren {
  ProductsCategoryProductRoute: typeof ProductsCategoryProductRoute
}

const ProductsCategoryRouteChildren: ProductsCategoryRouteChildren = {
  ProductsCategoryProductRoute: ProductsCategoryProductRoute,
}

const ProductsCategoryRouteWithChildren =
  ProductsCategoryRoute._addFileChildren(ProductsCategoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsCategoryRoute: ProductsCategoryRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
